#!/usr/bin/env zsh
# use functions to lazyload node & nvm: https://dev.to/voyeg3r/some-pearls-from-my-zshrc-282m

_load_nvm(){
  export NVM_DIR=~/.nvm
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}
#  virtual machine management
nvm() {
  unfunction $0
  _load_nvm
  nvm "$@"
}

node() {
  unfunction $0
  _load_nvm
  node "$@"
}

npm() {
  unfunction $0
  _load_nvm
  npm "$@"
}
